tailwind.config.js

added missing colors in tailwind.config.js

---

package-lock.json
package.json

adding formik packages

---

components/Hero.tsx
pages/home.tsx

Added Hero component and import to home

added Hero component and imported to home

---

components/BreakLine.tsx
components/ProjectsAccordian.tsx
pages/home.tsx
pages/index.tsx

deleted line break in index.tsx to compile correctly
Before:
After:

deleting merge conflict line break

---

pages/home.tsx

Din't change anything on the site itself, but updating PR for the testimonials placeholder
Before:
After:

Added Testimonials Place Holder file and commented out line in home file

---

.github/workflows/super-linter.yml
components/Footer.tsx

No ticket. Following up to add more linter steps.
Add new step to the github actions flow.
N/A

Add js/ts lint step to Github Actions

---

pages/index.tsx

Some styles related to responsiveness got changed accidentally.
Cherry picked commit from stable state right before we onboarded new contributors.
Before:
After:

Fix styles for large screens.

---

components/ContactForm.tsx
components/Testimonials.tsx
pages/stat-box.tsx

Fix several typescript errors blocking deploys.
Fixing errors that are raised when `npm run build && next export -o _static` is invoked by Digital Ocean.

Fix typescript errors

---

components/ContactForm.tsx
components/FormDiv.tsx

no new file was added, changed two files -- ContactForm and FormDiv
After:

styled contact form with responsiveness

---

components/Mission.tsx

./components/Mission.tsx
32:98 Error: ' can be escaped with &apos;, &lsquo;, &#39;, &rsquo;. react/no-unescaped-entities
Mission file
Before:
After:

edited single quote

---

components/Projects.tsx
pages/home.tsx

Title, graphic, header, and descriptive paragraph
Added all necessary elements. Text and image responsive in mobile and browser. Image however can not be moved any lower as the svg file contains a blank space below the visible graphic. 
Before:
N/A
After:
Mobile
Tablet:
Browser (xl)
Browser(lg)

9 add projects

---

pages/home.tsx

Adding Projects Component back into the home page
added tag for projects component into home. 
Before:
After:

adding projects content

---

components/ProjectsAccordian.tsx

No ticket for this issue. We noticed the deploys to digital ocean failing on typescript issues.
Add minimal changes to add any types to unblock deploys.
The /home page should be visible once the next deploy goes out.

Fix ts type issues.

---

components/Navbar.tsx

changed Navbar.tsx file
Before:
After:

connect to links and open in new tabs

---

pull_request_template.md

No ticket.
Updating the language and formatting for the pull request template.

Make pull request template more clear

---

__tests__/ContactForm.tsx
__tests__/IndexPage.jsx
components/ContactForm.tsx
jest.config.js
package-lock.json
package.json
pages/index.tsx
postcss.config.js
tailwind.config.js

Adding the testing library and boilerplate for writing JS tests.
Installed several packages required for writing tests in TS/React.
N/A

Add testing library.

---

components/ProjectsAccordian.tsx

- correcting interface object in projectAccordian component
- restructured interface statement to match projectsData const in projectsSection component
n/a

57 correct typescript error

---

components/Mission.tsx

updated Mission.tsx
Before:
After:
- Everything is centered
- H1 font larger than the paragraph
- Image is larger
- On a larger screen, image and text take up different width

changed text, padding to make it centered

---

components/byTheNumbers.tsx

updated byTheNumbers.tsx
Before:
After:
added margin on the left to make it looks more centered
changed the text color to white

changed text color and added margin

---

package-lock.json
pages/home.tsx

Attempt to fix package.json and package-lock.json asymmetry 
Currently build is failing on DO
simple npm install
N/A

npm install

---

components/BreakLine.tsx
components/ProjectsAccordian.tsx
components/ProjectsSection.tsx

77 update links in the project section

---

components/byTheNumbers.tsx

Updating content in byTheNumbers to reflect updated content in Figma
updated byTheNumbers content as necessary

updating content for byTheNumbers component

---

components/Footer.tsx

updated font. added correct hover state with border, adjusted padding/margins
Footer component

89 update footer section

---

components/ProjectsSection.tsx

Updating links in projects accordian
changes in projectSection component
N/A
N/A

updating links

---

components/ContactForm.tsx

Full name in hint text should be "First Name"
Message box gets greyed out (looks inactive)- remove this, should just be kept white
formatting changes made in the ContactForm component

updating formatting for fields

---

components/Navbar.tsx

- All in the navbar component, adjusted opacity of mobile menu, adjusted content/logo for medium screens
- Adjusted padding and donate button dimensions

85 adjust styling for navbar

---

components/Mission.tsx
components/Projects.tsx

Blurb + Accordion
Adjustments made in the projects component to match the mission component. (content is aligned in figma)

87 update projects section

---

__tests__/pages/api/contact.js

We need some boilerplate to build off the tests for contact for API.
Added a couple pending tests we can fill out once the email functionality is implemented.
No visible UI changes.

Add test boilerplate for contact API.

---

pages/api/contact.ts

Need to confirm the variable names for the email client.
Just added a block logging the environment variables in development to make sure you have the variables set.
N/A

Document email env variables

---

components/Navbar.tsx

##Describe the issue you are trying to resolve
fixing navbar, mobile navbar not functioning correctly
##Describe the changes you've made to resolve the issue
- created a sticky header for sm, med and large screens
- fixed z index 
- opacity could not be changed per figma based on new changes. 
https://github.com/specollective/spec-frontend/assets/66931010/b1bf7451-ebaf-40fe-88ce-5012cf99d81e
https://github.com/specollective/spec-frontend/assets/66931010/2ed8b5da-ad2c-41e6-ade7-85972ed10fa9
https://github.com/specollective/spec-frontend/assets/66931010/e2b0189a-4a37-4268-b693-9b71e3019a26

110 fix mobile navigation menu positioning and opacity

---

__tests__/pages/AboutPage.test.tsx
pages/aboutPage.tsx

Adding placeholder for About Page and adding smoke test to ensure it renders
Added the About Page and also added a test for in the testing folder.

104 add placeholder page for about page

---

__tests__/pages/OurTeamPage.test.tsx
pages/ourTeam.tsx

Creating placeholder and smoke test for Our Team Page
Added Our Team Page and added test.

113 add placeholder page for our team page

---

components/OurServices.tsx

Hiding OurServices component in mobile view
Adjusted OurServices components visibility to keep visible on med and large screens and invisible in mobile.

hiding OurServices component on mobile

---

components/ProjectsAccordian.tsx
constants/what-we-do-data.js

Updating Our Services Section with content per figma
Updates to format and content  of what-we-do-data constant, Projecs Accordian
**desktop:**
**mobile:**
mobile:
desktop

101 add finalized content to our services section

---

components/Testimonials.tsx

updated content for testimonials to include all recent testimonial quotes. 
Also checked the quote images on mobile but it's showing up as expected.
Update testimonials content
N/A

changing content for quotes

---

components/DonationTable.tsx
components/GetInvolved.tsx

Make some minor styling changes to incorporate review notes.
- Changed widths on some divs

Updating table row styling, width edits

---

components/Navbar.tsx
components/ProjectsAccordian.tsx

Changing font for Nav Bar and Our Services section. 
- changed font in NavBar component and Our Services component.

127 update font in navbar and services accordian

---

components/Hero.tsx
components/OurServices.tsx

Made edits to styling in Hero component. 
Mobile 
Desktop

129 fix hero content on mobile

---

components/Testimonials.tsx

- Fixing the white space on the right side on mobile
- Changed a portion of a carousel item class name to `justify-evenly`

Updating carousel item class

---

components/Background.tsx
components/HowWeWork.tsx
components/Mission.tsx
components/ProjectsAccordian.tsx
components/WhatWeDo.tsx

Mobile: Main content area updates, addresses ticket #136
Decrease padding, decrease margins to match Figma V2
Updates
- [x ] The margins are adjusted for the bulk of the content area (Mission, Background, How we work, What we do) to match to the rest of the margins throughout the page. In the attached picture the red lines are to show margins, for reference.
- [x ] In this area I also left aligned and stretched the text to width. Previously it was centered to the page. Attached 2nd picture to show the previous and new margins/paddings/alignment(I didn't change any files it looks like this was already done)
- [ x] Padding in between each section was also minimized (so we dont have so much unnecessary white space). This is shown by the blue boxes for reference.

Mobile: Main content area updates 

---

components/GetInvolved.tsx

https://github.com/specollective/spec-frontend/issues/133
- [ x] The Get Involved cards should be all the same size. The Work with Us card should be bigger to match the others
- [ x] I removed "Join us in making a difference" in the Donate card. And I think for mobile we can keep the illustration instead of the tiers. The tiers might be too cluttered on the small screen

Fix card sizing and hidden text on mobile

---

components/byTheNumbers.tsx

Resolves https://github.com/specollective/spec-frontend/issues/137
- [x ] By the Numbers content (within the white boxes) was updated on both mobile and desktop

Update content in by the numbers cards

---

components/GetInvolved.tsx

Addresses https://github.com/specollective/spec-frontend/issues/142

Align contact us links

---

components/Carousel/Carousel.tsx
components/Carousel/CarouselItemContainer.tsx
components/HomeSection.tsx
components/ReadMore.tsx
components/Testimonials.tsx
constants/testimonials-data.js
pages/_app.tsx
pages/home.tsx
styles/sections.js

Resolve multiple issues related to the carousels and testimonials components.
Created a component that maintained the required data properties and ids dynamically set to allow the tailwind element to work properly.

Clean up carousel implementation.

---

components/Background.tsx
components/HowWeWork.tsx
components/WhatWeDo.tsx

Final copy changes.

---

components/DonationTable.tsx
components/GetInvolved/DesktopGetInvolved.tsx
components/HomeSection.tsx
components/Typography/Heading.tsx

- Fix component styling / margins / padding / etc. on larger responsive screens for Desktop
-  components/DonationTable.tsx 
-  components/GetInvolved/DesktopGetInvolved.tsx 
-  components/HomeSection.tsx 
-  components/Typography/Heading.tsx
Tested on a 24'in (diagonal) monitor

Styling fixes on Desktop for larger breakpoints

---

components/Background.tsx
components/ByTheNumbers.tsx
components/HowWeWork.tsx
components/Mission.tsx

This makes minor copy updates to a few components.
- components/Background.tsx 
- components/ByTheNumbers.tsx 
- components/HowWeWork.tsx 
- components/Mission.tsx

Typo and grammar fixes

---

components/DonationTable.tsx
components/GetInvolved/DesktopGetInvolved.tsx
components/HomeSection.tsx
components/Mission.tsx

Minor style fixes for different-sized devices.
Mainly tweaking breakpoints for layouts.

Minor style fixes.

---

components/DonationTable.tsx

- Shifted text to the right
- components/DonationTable.tsx

Shifted donation table text to the right

---

pages/index.tsx

Data fetching wasn't working in production. We need to use getServerSideProps instead of static props.
N/A

Fix home data fetching.

---

components/BreakLine.tsx
components/Slider.tsx
package-lock.json
package.json
pages/_app.tsx
tailwind.config.js

Clean up slider interactions and remove `tw-elements`.

Clean up slider interactions.

---

components/AppHead.tsx

Add Google Analytics.

---

components/HowWeWork.tsx

Update fiscal sponosrship information.
Simple copy change on landing page.
Just adding copy about Hack Club Bank

Update "How We Work" section
